### PR TITLE
Add assumedTestBase to give machine readable base URI information.

### PR DESCRIPTION
**Pull request by afs**
This is a PR to branch `fix-default-base`.

### CODE REVIEW

**Review by Tpt — COMMENTED** [review]
Thank you for pushing that. I believe we also need to set the base URI for `rdf-xml`.

**Comment by afs** [comment]
Added for rdf-xml (but untested - the Jena build runs the WG test suite, not this copy.)

I intentionally didn't add it to `rdf-n-triples` and `rdf-n-quads` as it does not apply.
I didn't add it to `rdf-mt` because the README says it doesn't matter.

**Review by gkellogg — CHANGES_REQUESTED** [review]
The [JSON-LD Expansion tests](https://github.com/w3c/json-ld-api/blob/main/tests/expand-manifest.jsonld) do this with a `baseIri` property on the manifest, but that's not really a well-defined term (it expands to `<https://w3c.github.io/json-ld-api/tests/vocab#baseIri>`.

I'm fine with `assumedTestBase`, but we should add an entry to https://github.com/w3c/rdf-tests/blob/main/ns/test-manifest.ttl describing the property to eventually by synchronized to http://www.w3.org/2001/sw/DataAccess/tests/test-manifest.

**Review by gkellogg — APPROVED** [review]
Added entry to the test manifest.

**Pull request merged**
