### PR TITLE
Add IRI resolution tests (subset)

### PR DESCRIPTION
**Pull request by RubenVerborgh**
Same as #13, but only adds tests 1, 2, 7, and 8 as discussed in #6.

### CODE REVIEW

**Comment by gkellogg** [comment]
The branch seems to be missing some Turtle files:

* IRI-resolution-03.ttl/nt
* IRI-resolution-04.ttl/nt
* IRI-resolution-05.ttl/nt
* IRI-resolution-06.ttl/nt

**Comment by gkellogg** [comment]
(Looks like equivalent TriG files are also missing.

**Comment by RubenVerborgh** [comment]
That's on purpose, but I forgot to edit the manifest. Will do!

**Comment by RubenVerborgh** [comment]
Fixed. This pull requests exists so people can test the cases of #13 for which there is consensus, as [requested by @afs](https://lists.w3.org/Archives/Public/public-rdf-tests/2016Jan/0005.html).

**Comment by gkellogg** [comment]
Those all work for me, +1 to merge after comments go through.

**Pull request merged**
