### PR TITLE
Removed function tests strdt03 and strlang03 to align with RDF 1.1 (#19)

### PR DESCRIPTION
**Pull request by kasei**
Removes tests :strdt03 and :strlang03 which fail under RDF 1.1 systems. Replaces them with :strdt03-rdf11 and :strlang03-rdf11 which use the same data and query, but updated expected result data based on RDF 1.1 semantics.

The SPARQL 1.1 test suite expects "abc"^^xsd:string and "DEF"^^xsd:string to produce an error when passed to STRDT and STRLANG, leading to ?str1 being unbound in these tests. This is because STRDT and STRLANG expect their first argument to a "simple literal". However, in RDF 1.1 "simple literals" are merely syntactic sugar for xsd:string datatyped literals. Therefore, both of these literals should be acceptable to STRDT and STRLANG, yielding values bound to ?str1.

### CODE REVIEW

**Comment by gkellogg** [comment]
Are there other changes we should batch up? Pulling this requires sending out to public-rdf-tests@w3.org and public-sparql-dev@w3.org in a call for consensus, which I will perform. It would be good to optimize the attention of readers.

**Comment by kasei** [comment]
I'm confident that these are the only changes relating to RDF 1.1 and SPARQL 1.1 Query. @afs may have thoughts on the other issues he mentioned, but I would think any changes related to those ought to be in a separate issue/PR anyway.

**Comment by gkellogg** [comment]
[Call for consensus](https://lists.w3.org/Archives/Public/public-rdf-tests/2015Nov/0002.html) generated no negative feedback.

**Comment by afs** [comment]
By the way, these changes are not to do with RDF 1.1 conformance.  They are just as wrong for SPARQL 1.1 / RDF 1.0.

**Pull request merged**
