### PR TITLE
GH-84: SPARQL reorg - final step

### PR DESCRIPTION
**Pull request by afs**
This is the final step of issue #84.

It removes the top level `/sparql11` tree which was SPARQL 1.0 ("data-r2") and SPARQL 1.1 WG tests.. The trees `/sparql/sparq10` and `/sparql/sparq11` were copied from `/sparql11`.

All SPARQL tests will be under `/sparql` : `/sparql/sparql10`, `/sparql/sparql11`, `/sparql/sparql12`

cc: @Tpt (I can't add you as a reviewer - are you a member of the CG?)
Later:  You are a member - but don't appear as a choice of review.

### CODE REVIEW

**Review by gkellogg — APPROVED** [review]

**Comment by gkellogg** [comment]
We'll need to do a similar reorganization for the RDF tests.

**Comment by Tpt** [comment]
+1 to the change.

> cc: @Tpt (I can't add you as a reviewer - are you a member of the CG?)

I am a member of the CG. @gkellogg tried to add me a few months ago but it failed with a "not a member error". Now that I already have access to other w3c repos it might be worth it to try again.

**Review by rubensworks — APPROVED** [review]

**Review by domel — APPROVED** [review]

**Comment by gkellogg** [comment]
@pchampin will  need to sort out permissions for RDF-star WG access.

**Comment by pchampin** [comment]
> @pchampin will need to sort out permissions for RDF-star WG access.

@gkellogg what exactly do you mean by that? Do you want me to give permissions to RDF-star WG participants to this repo? If so, to which level? (Triage? Write?)

**Comment by afs** [comment]
I think it is about @Tpt access - https://github.com/w3c/rdf-tests/pull/103#issuecomment-1636001682

**Comment by gkellogg** [comment]
Yes, RDF-star WG members should have access to the repo, similar to how they have access to other WG repositories. I think this generally includes "Write" access, but could be "Triage". "Write" access is more useful for people who may create PRs.

**Pull request merged**
